### ISSUE TITLE
Fails with an error

### ISSUE THREAD

**Issue by harizvi** [atomontage/osa-chrome#1] opened 2020-05-14 01:21 UTC
Following up from my reddit post. 

I'm running mituhara's emacs mac-port: 
`
(emacs-version)
"GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4)
 of 2020-03-24"
`

Started this emacs with -Q, load-file both osa.el and osa-chrome.el, and then M-x osa-chrome: 

`Debugger entered--Lisp error: (error "Error on line 10: Error: An error occurred." (number . -1743) (range 435 . 75))
  mac-osa-script("// Sourced from: /Users/hrizvi/.emacs.d/gits/osa-chrome.git/scripts/get-tabs-single.js\n// This is free and unencumbered software released into the public domain.\n\nfunction get_tabs_single(chrome_app_name)\n{\n    // Retrieves all tabs from all windows belonging to a single Chrome\n    // instance (process). This function should be what most users need.\n    const name  = chrome_app_name;\n    const se    = Application('System Events');\n    const procs = se.applicationProcesses.whose({name: name}).unixId.get();\n    let out     = {};\n\n\n    if (procs.length !== 0) {\n        // Note that the following works if there's only one Chrome process\n        // currently running. Otherwise it's possible that the PID returned\n        // from System Events will not match the Chrome instance retrieved\n        // through Application(). AFAIK it is not possible to get a correct\n        // reference to an application by PID through Application(), one\n        // has to use System Events.\n        const pid    = procs[0];\n        const chrome = Application(name);\n\n        // These are lazy-evaluated selectors that return results in one batch,\n        // minimizing the number of Apple event calls. A standard loop to\n        // retrieve each tab url/title would be noticeably slower.\n        const tabs    = [chrome.windows.tabs.id.get(),\n                         chrome.windows.tabs.url.get(),\n                         chrome.windows.tabs.title.get()];\n\n        const windows = chrome.windows.id.get();\n        const active  = chrome.windows.activeTab.id.get();\n        out[pid]      = [windows, active, tabs];\n    }\n\n    return out;\n}" "JavaScript" nil t "get_tabs_single" ("utxt" . "G\0o\0o\0g\0l\0\ e\0 \0\ C\0h\0r\0o\0m\0\ e\0") ("fals" . ""))
  apply(mac-osa-script "// Sourced from: /Users/hrizvi/.emacs.d/gits/osa-chrome.git/scripts/get-tabs-single.js\n// This is free and unencumbered software released into the public domain.\n\nfunction get_tabs_single(chrome_app_name)\n{\n    // Retrieves all tabs from all windows belonging to a single Chrome\n    // instance (process). This function should be what most users need.\n    const name  = chrome_app_name;\n    const se    = Application('System Events');\n    const procs = se.applicationProcesses.whose({name: name}).unixId.get();\n    let out     = {};\n\n\n    if (procs.length !== 0) {\n        // Note that the following works if there's only one Chrome process\n        // currently running. Otherwise it's possible that the PID returned\n        // from System Events will not match the Chrome instance retrieved\n        // through Application(). AFAIK it is not possible to get a correct\n        // reference to an application by PID through Application(), one\n        // has to use System Events.\n        const pid    = procs[0];\n        const chrome = Application(name);\n\n        // These are lazy-evaluated selectors that return results in one batch,\n        // minimizing the number of Apple event calls. A standard loop to\n        // retrieve each tab url/title would be noticeably slower.\n        const tabs    = [chrome.windows.tabs.id.get(),\n                         chrome.windows.tabs.url.get(),\n                         chrome.windows.tabs.title.get()];\n\n        const windows = chrome.windows.id.get();\n        const active  = chrome.windows.activeTab.id.get();\n        out[pid]      = [windows, active, tabs];\n    }\n\n    return out;\n}" "JavaScript" nil t "get_tabs_single" (("utxt" . "G\0o\0o\0g\0l\0\ e\0 \0\ C\0h\0r\0o\0m\0\ e\0") ("fals" . "")))
  (let ((res (apply (function mac-osa-script) src lang nil t call args))) (if unpack (osa-unpack res) res))
  (let ((src (string-to-multibyte src)) (args (and call args (cl-mapcar (function osa-pack) args)))) (let ((res (apply (function mac-osa-script) src lang nil t call args))) (if unpack (osa-unpack res) res)))
  (progn (if call (progn (progn (or (stringp call) (cl--assertion-failed (quote (stringp call)) nil (list call) (list))) nil))) (if args (progn (progn (or (listp args) (cl--assertion-failed (quote (listp args)) nil (list args) (list))) nil))) (progn (or (seq-contains (quote ("AppleScript" "JavaScript")) lang) (cl--assertion-failed (quote (seq-contains (quote ("AppleScript" "JavaScript")) lang)) nil (list lang) (list))) nil) (let ((src (string-to-multibyte src)) (args (and call args (cl-mapcar (function osa-pack) args)))) (let ((res (apply (function mac-osa-script) src lang nil t call args))) (if unpack (osa-unpack res) res))))
  (let* ((unpack (car (cdr (or (plist-member --cl-rest-- (quote :unpack)) (quote (nil t)))))) (lang (car (cdr (or (plist-member --cl-rest-- (quote :lang)) (quote (nil "AppleScript")))))) (call (car (cdr (plist-member --cl-rest-- (quote :call))))) (args (car (cdr (plist-member --cl-rest-- (quote :args)))))) (progn (if call (progn (progn (or (stringp call) (cl--assertion-failed (quote ...) nil (list call) (list))) nil))) (if args (progn (progn (or (listp args) (cl--assertion-failed (quote ...) nil (list args) (list))) nil))) (progn (or (seq-contains (quote ("AppleScript" "JavaScript")) lang) (cl--assertion-failed (quote (seq-contains (quote ...) lang)) nil (list lang) (list))) nil) (let ((src (string-to-multibyte src)) (args (and call args (cl-mapcar (function osa-pack) args)))) (let ((res (apply (function mac-osa-script) src lang nil t call args))) (if unpack (osa-unpack res) res)))))
  osa-eval("// Sourced from: /Users/hrizvi/.emacs.d/gits/osa-chrome.git/scripts/get-tabs-single.js\n// This is free and unencumbered software released into the public domain.\n\nfunction get_tabs_single(chrome_app_name)\n{\n    // Retrieves all tabs from all windows belonging to a single Chrome\n    // instance (process). This function should be what most users need.\n    const name  = chrome_app_name;\n    const se    = Application('System Events');\n    const procs = se.applicationProcesses.whose({name: name}).unixId.get();\n    let out     = {};\n\n\n    if (procs.length !== 0) {\n        // Note that the following works if there's only one Chrome process\n        // currently running. Otherwise it's possible that the PID returned\n        // from System Events will not match the Chrome instance retrieved\n        // through Application(). AFAIK it is not possible to get a correct\n        // reference to an application by PID through Application(), one\n        // has to use System Events.\n        const pid    = procs[0];\n        const chrome = Application(name);\n\n        // These are lazy-evaluated selectors that return results in one batch,\n        // minimizing the number of Apple event calls. A standard loop to\n        // retrieve each tab url/title would be noticeably slower.\n        const tabs    = [chrome.windows.tabs.id.get(),\n                         chrome.windows.tabs.url.get(),\n                         chrome.windows.tabs.title.get()];\n\n        const windows = chrome.windows.id.get();\n        const active  = chrome.windows.activeTab.id.get();\n        out[pid]      = [windows, active, tabs];\n    }\n\n    return out;\n}" :lang "JavaScript" :call "get_tabs_single" :args ("Google Chrome" nil))
  apply(osa-eval "// Sourced from: /Users/hrizvi/.emacs.d/gits/osa-chrome.git/scripts/get-tabs-single.js\n// This is free and unencumbered software released into the public domain.\n\nfunction get_tabs_single(chrome_app_name)\n{\n    // Retrieves all tabs from all windows belonging to a single Chrome\n    // instance (process). This function should be what most users need.\n    const name  = chrome_app_name;\n    const se    = Application('System Events');\n    const procs = se.applicationProcesses.whose({name: name}).unixId.get();\n    let out     = {};\n\n\n    if (procs.length !== 0) {\n        // Note that the following works if there's only one Chrome process\n        // currently running. Otherwise it's possible that the PID returned\n        // from System Events will not match the Chrome instance retrieved\n        // through Application(). AFAIK it is not possible to get a correct\n        // reference to an application by PID through Application(), one\n        // has to use System Events.\n        const pid    = procs[0];\n        const chrome = Application(name);\n\n        // These are lazy-evaluated selectors that return results in one batch,\n        // minimizing the number of Apple event calls. A standard loop to\n        // retrieve each tab url/title would be noticeably slower.\n        const tabs    = [chrome.windows.tabs.id.get(),\n                         chrome.windows.tabs.url.get(),\n                         chrome.windows.tabs.title.get()];\n\n        const windows = chrome.windows.id.get();\n        const active  = chrome.windows.activeTab.id.get();\n        out[pid]      = [windows, active, tabs];\n    }\n\n    return out;\n}" (:lang "JavaScript" :call "get_tabs_single" :args ("Google Chrome" nil)))
  (let ((src (mapconcat --cl-slurp-- (append (if (not (listp include)) (list include) include) (list path)) "\n\n"))) (if debug (progn (save-current-buffer (set-buffer (generate-new-buffer "*osa-eval-file*")) (insert src) (goto-char (point-min)) (message "osa-eval: %d characters written to buffer %s" (buffer-size) (buffer-name))))) (apply (function osa-eval) src rest))
  (progn (let ((src (mapconcat --cl-slurp-- (append (if (not ...) (list include) include) (list path)) "\n\n"))) (if debug (progn (save-current-buffer (set-buffer (generate-new-buffer "*osa-eval-file*")) (insert src) (goto-char (point-min)) (message "osa-eval: %d characters written to buffer %s" (buffer-size) (buffer-name))))) (apply (function osa-eval) src rest)))
  (let* ((--cl-slurp-- (function (lambda (p) (let ((temp-buffer ...)) (save-current-buffer (set-buffer temp-buffer) (unwind-protect ... ...))))))) (progn (let ((src (mapconcat --cl-slurp-- (append (if ... ... include) (list path)) "\n\n"))) (if debug (progn (save-current-buffer (set-buffer (generate-new-buffer "*osa-eval-file*")) (insert src) (goto-char (point-min)) (message "osa-eval: %d characters written to buffer %s" (buffer-size) (buffer-name))))) (apply (function osa-eval) src rest))))
  (progn (progn (or (seq-contains (quote ("AppleScript" "JavaScript")) lang) (cl--assertion-failed (quote (seq-contains (quote ("AppleScript" "JavaScript")) lang)) nil (list lang) (list))) nil) (let* ((--cl-slurp-- (function (lambda (p) (let (...) (save-current-buffer ... ...)))))) (progn (let ((src (mapconcat --cl-slurp-- (append ... ...) "\n\n"))) (if debug (progn (save-current-buffer (set-buffer ...) (insert src) (goto-char ...) (message "osa-eval: %d characters written to buffer %s" ... ...)))) (apply (function osa-eval) src rest)))))
  (let* ((lang (car (cdr (or (plist-member rest (quote :lang)) (quote (nil "AppleScript")))))) (include (car (cdr (plist-member rest (quote :include))))) (debug (car (cdr (plist-member rest (quote :debug)))))) (progn (progn (or (seq-contains (quote ("AppleScript" "JavaScript")) lang) (cl--assertion-failed (quote (seq-contains (quote ...) lang)) nil (list lang) (list))) nil) (let* ((--cl-slurp-- (function (lambda (p) (let ... ...))))) (progn (let ((src (mapconcat --cl-slurp-- ... "\n\n"))) (if debug (progn (save-current-buffer ... ... ... ...))) (apply (function osa-eval) src rest))))))
  osa-eval-file("/Users/hrizvi/.emacs.d/gits/osa-chrome.git/scripts/get-tabs-single.js" :lang "JavaScript" :call "get_tabs_single" :args ("Google Chrome" nil))
  (let* ((osa-strict-unpacking t) (ret (osa-eval-file (osa-chrome--find-script (if osa-chrome-single-instance "get-tabs-single.js" "get-tabs-multi.js")) :lang "JavaScript" :call (if osa-chrome-single-instance "get_tabs_single" "get_tabs_multi") :args (list osa-chrome-application-name (if osa-chrome-single-instance nil (osa-chrome--machine-url)))))) (let* ((G0 (and t (cdr (assoc "error" ret)))) (G1 (and G0 (cdr (assoc "error-data" ret))))) (if G1 (osa-chrome--message "%s%s" G0 (if G1 (format " [%s]" G1) "")) ret)))
  osa-chrome-get-tabs()
  (osa-chrome--reindex-tabs (osa-chrome-get-tabs))
  (progn (osa-chrome--start-timer) (osa-chrome--reindex-tabs (osa-chrome-get-tabs)) (osa-chrome--filter-tabs))
  (unwind-protect (progn (osa-chrome--start-timer) (osa-chrome--reindex-tabs (osa-chrome-get-tabs)) (osa-chrome--filter-tabs)) (osa-chrome--stop-timer) (setq osa-chrome--header-update t))
  osa-chrome-mode()
  (if (eq major-mode (quote osa-chrome-mode)) nil (osa-chrome-mode))
  (let ((buf (get-buffer-create "*chrome-tabs*"))) (switch-to-buffer buf) (if (eq major-mode (quote osa-chrome-mode)) nil (osa-chrome-mode)))
  osa-chrome()
  funcall-interactively(osa-chrome)
  call-interactively(osa-chrome record nil)
  command-execute(osa-chrome record)
  execute-extended-command(nil "osa-chrome" "os")
  funcall-interactively(execute-extended-command nil "osa-chrome" "os")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by atomontage** [comment] 2020-05-14 01:30
Do this (after you load osa)

```
M-x ielm

ELISP> (osa-eval "const chrome = Application('Google Chrome'); chrome" :lang "JavaScript")
```
What does it return?

**Comment by atomontage** [comment] 2020-05-14 01:50
One more thing to try is going to macOS System Preferences, under Privacy tab, click on Accessibility on the left, and scroll through the list on the right (allow the apps below to control your computer. See if Emacs is there and selected. If not try adding it.

**Comment by atomontage** [comment] 2020-05-14 02:58
I reproduced your issue here, it's an OS permission problem that happens with Mojave and I assume Catalina, since they started locking things down.

First, if you've downloaded an Emacs release binary from railwaycat's github page, that didn't work for me. He must have packaged it wrong because I never managed to get the permission dialog that's supposed to popup the first time Emacs tries to use Apple Events.

So I suggest you install Emacs from source (brew tap .. brew install ..), assuming you haven't done so. Then, you should get a popup asking you to allow Emacs to control other applications.

If you go to System Preferences, Security & Privacy, Automation / Privacy tab, you should see Emacs be present with the relevant permissions enabled.

![Screen Shot 2020-05-13 at 22 52 52](https://user-images.githubusercontent.com/453886/81887450-171d6e00-956d-11ea-85a3-8de6bd76643f.png)

**Comment by harizvi** [comment] 2020-05-14 15:33
> Do this (after you load osa)
> 
> ```
> M-x ielm
> 
> ELISP> (osa-eval "const chrome = Application('Google Chrome'); chrome" :lang "JavaScript")
> ```
> 
> What does it return?

This returns with: 
condition-case: No primary method: osa--unpack, nil, "

**Comment by harizvi** [comment] 2020-05-14 15:34
> One more thing to try is going to macOS System Preferences, under Privacy tab, click on Accessibility on the left, and scroll through the list on the right (allow the apps below to control your computer. See if Emacs is there and selected. If not try adding it.

Yes, I've added this to the Accessibility options.

**Comment by harizvi** [comment] 2020-05-14 15:37
> never

Yes, I downloaded the packaged app. I did add to the Accessibility section manually, and the Automation / Privacy already had it (perhaps from the previous installs). 

I'll go through the build process, and then ping if I still have issues. 

Thanks for your quick responses @atomontage !

**Comment by harizvi** [comment] 2020-05-19 05:47
Finally got a chance to follow up. After rebuilding Emacs, it works fine. Thanks. 

It shows all my tabs, from all profiles. Is there a way to show the profile info along with the tab?

**Comment by atomontage** [comment] 2020-05-19 13:43
Ok I am going to close this then.

I could show the Process ID, but if you mean profile directory I don't think that's exported through the API I'm using. I'll have a look though.

**Closed as completed by atomontage** 2020-05-19 13:43 UTC

**Comment by x-ji** [comment] 2022-03-13 16:56
I also had the `-1743` error with railwaycat's port when trying to delete a file via `magit`. Reinstalling from brew didn't solve the problem. What finally let Emacs request automation permission was to use https://github.com/kaz-yos/reveal-in-osx-finder and try to open a file in Finder. It correctly asked for permission when I tried it, after which I was finally able to delete files via `magit`. Commenting here in case somebody runs into a similar issue.
